version: '3'

services:

  rabbitmq1:
    build: .
    #    hostname: "rabbitmq1"
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    container_name: rabbitmq_federation_test_1
  rabbitmq2:
    build: .
    links:
      - rabbitmq1
    hostname: "rabbit2"
    ports:
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    container_name: rabbitmq_federation_test_2
